# Generated by Django 2.2 on 2020-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200910_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
