# Generated by Django 2.2 on 2020-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200911_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
