# Generated by Django 2.2 on 2020-09-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_blog', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='RSContactMessage',
        ),
    ]
