# Generated by Django 2.2 on 2020-09-22 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_blog', '0003_auto_20200911_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsblogpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
